### ISSUE TITLE
after_event not working properly

### ISSUE THREAD

**Issue by c-ali** [da-h/miniflask#78] opened 2021-09-03 09:56 UTC
I encountered a bug when registering an after_"event" and adding "event" to the function parameters eg.

>     mf.register_event('after_backward', test, unique=False)

> def test(event):
>    pass

I have no problems when including "state".  I get the following stacktrace: https://pastebin.com/Q9v1ettP.

**Comment by da-h** [comment] 2021-09-03 10:01
Please provide information on your current setup.
What version of miniflask are you using, etc?

**Comment by c-ali** [comment] 2021-09-03 10:04
Using Miniflask v2.1.0, pytorch v1.9.0 and python 3.9.6.

**Comment by da-h** [comment] 2021-11-09 14:36
This issue is a duplicate of #80 and has been fixed with PR #82.

**Closed by da-h** 2021-11-09 14:36 UTC
